teamDiv = {
  'Air Force Falcons': 'Mountain',
 'Akron Zips': 'East',
 'Alabama Crimson Tide': 'West',
 'Appalachian State Mountaineers': 'East',
 'Arizona State Sun Devils': 'South',
 'Arizona Wildcats': 'South',
 'Arkansas Razorbacks': 'West',
 'Arkansas State Red Wolves': 'West',
 'Army Black Knights': '',
 'Auburn Tigers': 'West',
 'Ball State Cardinals': 'West',
 'Baylor Bears': '',
 'Boise State Broncos': 'Mountain',
 'Boston College Eagles': 'Atlantic',
 'Bowling Green Falcons': 'East',
 'Brigham Young Cougars': '',
 'Buffalo Bulls': 'East',
 'California Golden Bears': 'North',
 'Central Michigan Chippewas': 'West',
 'Charlotte 49ers': 'East',
 'Cincinnati Bearcats': 'East',
 'Clemson Tigers': 'Atlantic',
 'Coastal Carolina Chanticleers': 'East',
 'Colorado Buffaloes': 'South',
 'Colorado State Rams': 'Mountain',
 'Connecticut Huskies': 'East',
 'Duke Blue Devils': 'Coastal',
 'East Carolina Pirates': 'East',
 'Eastern Michigan Eagles': 'West',
 'FIU Panthers': 'East',
 'Florida Atlantic Owls': 'East',
 'Florida Gators': 'East',
 'Florida State Seminoles': 'Atlantic',
 'Fresno State Bulldogs': 'West',
 'Georgia Bulldogs': 'East',
 'Georgia Southern Eagles': 'East',
 'Georgia State Panthers': 'East',
 'Georgia Tech Yellow Jackets': 'Coastal',
 'Hawaii Rainbow Warriors': 'West',
 'Houston Cougars': 'West',
 'Idaho Vandals': '',
 'Illinois Fighting Illini': 'West',
 'Indiana Hoosiers': 'East',
 'Iowa Hawkeyes': 'West',
 'Iowa State Cyclones': '',
 'Kansas Jayhawks': '',
 'Kansas State Wildcats': '',
 'Kent State Golden Flashes': 'East',
 'Kentucky Wildcats': 'East',
 'LSU Tigers': 'West',
 'Louisiana Tech Bulldogs': '',
 "Louisiana-Lafayette Ragin' Cajuns": 'West',
 'Louisiana-Monroe Warhawks': 'West',
 'Louisville Cardinals': 'Atlantic',
 'Marshall Thundering Herd': 'East',
 'Maryland Terrapins': 'East',
 'Massachusetts Minutemen': '',
 'Memphis Tigers': 'West',
 'Miami (FL) Hurricanes': 'Coastal',
 'Miami (OH) RedHawks': 'East',
 'Michigan State Spartans': 'East',
 'Michigan Wolverines': 'East',
 'Middle Tennessee Blue Raiders': 'East',
 'Minnesota Golden Gophers': 'West',
 'Mississippi Rebels': 'West',
 'Mississippi State Bulldogs': 'West',
 'Missouri Tigers': 'East',
 'Navy Midshipmen': 'West',
 'Nebraska Cornhuskers': 'West',
 'Nevada Wolf Pack': 'West',
 'New Mexico Lobos': 'Mountain',
 'New Mexico State Aggies': '',
 'North Carolina State Wolfpack': 'Atlantic',
 'North Carolina Tar Heels': 'Coastal',
 'North Texas Mean Green': 'West',
 'Northern Illinois Huskies': 'West',
 'Northwestern Wildcats': 'West',
 'Notre Dame Fighting Irish': '',
 'Ohio Bobcats': 'East',
 'Ohio State Buckeyes': 'East',
 'Oklahoma Sooners': '',
 'Oklahoma State Cowboys': '',
 'Old Dominion Monarchs': 'East',
 'Oregon Ducks': 'North',
 'Oregon State Beavers': 'North',
 'Penn State Nittany Lions': 'East',
 'Pittsburgh Panthers': 'Coastal',
 'Purdue Boilermakers': 'West',
 'Rice Owls': 'West',
 'Rutgers Scarlet Knights': 'East',
 'San Diego State Aztecs': 'West',
 'San Jose State Spartans': 'West',
 'South Alabama Jaguars': 'West',
 'South Carolina Gamecocks': 'East',
 'South Florida Bulls': 'East',
 'Southern Methodist Mustangs': 'West',
 'Southern Miss Golden Eagles': 'West',
 'Stanford Cardinal': 'North',
 'Syracuse Orange': 'Atlantic',
 'TCU Horned Frogs': '',
 'Temple Owls': 'East',
 'Tennessee Volunteers': 'East',
 'Texas A&M Aggies': 'West',
 'Texas Longhorns': '',
 'Texas State Bobcats': 'West',
 'Texas Tech Red Raiders': '',
 'Texas-San Antonio Roadrunners': 'West',
 'Toledo Rockets': 'West',
 'Troy Trojans': 'East',
 'Tulane Green Wave': 'West',
 'Tulsa Golden Hurricane': 'West',
 'UAB Blazers': 'West',
 'UCF Knights': 'East',
 'UCLA Bruins': 'South',
 'UNLV Rebels': 'West',
 'USC Trojans': 'South',
 'UTEP Miners': 'West',
 'Utah State Aggies': 'Mountain',
 'Utah Utes': 'South',
 'Vanderbilt Commodores': 'East',
 'Virginia Cavaliers': 'Coastal',
 'Virginia Tech Hokies': 'Coastal',
 'Wake Forest Demon Deacons': 'Atlantic',
 'Washington Huskies': 'North',
 'Washington State Cougars': 'North',
 'West Virginia Mountaineers': '',
 'Western Kentucky Hilltoppers': 'East',
 'Western Michigan Broncos': 'West',
 'Wisconsin Badgers': 'West',
 'Wyoming Cowboys': 'Mountain'
}
