idDic = {
    'Air Force Falcons': '001',
    'Akron Zips': '002',
    'Alabama Crimson Tide': '003',
    'Appalachian State Mountaineers': '004',
    'Arizona State Sun Devils': '006',
    'Arizona Wildcats': '005',
    'Arkansas Razorbacks': '007',
    'Arkansas State Red Wolves': '008',
    'Army Black Knights': '009',
    'Auburn Tigers': '010',
    'Ball State Cardinals': '011',
    'Baylor Bears': '012',
    'Boise State Broncos': '013',
    'Boston College Eagles': '014',
    'Bowling Green Falcons': '015',
    'Brigham Young Cougars': '017',
    'Buffalo Bulls': '016',
    'California Golden Bears': '018',
    'Central Michigan Chippewas': '019',
    'Charlotte 49ers': '020',
    'Cincinnati Bearcats': '021',
    'Clemson Tigers': '022',
    'Coastal Carolina Chanticleers': '023',
    'Colorado Buffaloes': '024',
    'Colorado State Rams': '025',
    'Connecticut Huskies': '026',
    'Duke Blue Devils': '027',
    'East Carolina Pirates': '028',
    'Eastern Michigan Eagles': '029',
    'FIU Panthers': '030',
    'Florida Atlantic Owls': '032',
    'Florida Gators': '031',
    'Florida State Seminoles': '033',
    'Fresno State Bulldogs': '034',
    'Georgia Bulldogs': '035',
    'Georgia Southern Eagles': '036',
    'Georgia State Panthers': '037',
    'Georgia Tech Yellow Jackets': '038',
    'Hawaii Rainbow Warriors': '039',
    'Houston Cougars': '040',
    'Idaho Vandals': '041',
    'Illinois Fighting Illini': '042',
    'Indiana Hoosiers': '043',
    'Iowa Hawkeyes': '044',
    'Iowa State Cyclones': '045',
    'Kansas Jayhawks': '046',
    'Kansas State Wildcats': '047',
    'Kent State Golden Flashes': '048',
    'Kentucky Wildcats': '049',
    'LSU Tigers': '054',
    'Louisiana Tech Bulldogs': '050',
    "Louisiana-Lafayette Ragin' Cajuns": '051',
    'Louisiana-Monroe Warhawks': '052',
    'Louisville Cardinals': '053',
    'Marshall Thundering Herd': '055',
    'Maryland Terrapins': '056',
    'Massachusetts Minutemen': '057',
    'Memphis Tigers': '058',
    'Miami (FL) Hurricanes': '059',
    'Miami (OH) RedHawks': '060',
    'Michigan State Spartans': '062',
    'Michigan Wolverines': '061',
    'Middle Tennessee Blue Raiders': '063',
    'Minnesota Golden Gophers': '064',
    'Mississippi Rebels': '065',
    'Mississippi State Bulldogs': '066',
    'Missouri Tigers': '067',
    'Navy Midshipmen': '068',
    'Nebraska Cornhuskers': '070',
    'Nevada Wolf Pack': '071',
    'New Mexico Lobos': '072',
    'New Mexico State Aggies': '073',
    'North Carolina State Wolfpack': '069',
    'North Carolina Tar Heels': '075',
    'North Texas Mean Green': '076',
    'Northern Illinois Huskies': '074',
    'Northwestern Wildcats': '077',
    'Notre Dame Fighting Irish': '078',
    'Ohio Bobcats': '079',
    'Ohio State Buckeyes': '080',
    'Oklahoma Sooners': '081',
    'Oklahoma State Cowboys': '082',
    'Old Dominion Monarchs': '083',
    'Oregon Ducks': '084',
    'Oregon State Beavers': '085',
    'Penn State Nittany Lions': '086',
    'Pittsburgh Panthers': '087',
    'Purdue Boilermakers': '088',
    'Rice Owls': '089',
    'Rutgers Scarlet Knights': '090',
    'San Diego State Aztecs': '091',
    'San Jose State Spartans': '092',
    'South Alabama Jaguars': '093',
    'South Carolina Gamecocks': '094',
    'South Florida Bulls': '095',
    'Southern Methodist Mustangs': '097',
    'Southern Miss Golden Eagles': '098',
    'Stanford Cardinal': '099',
    'Syracuse Orange': '100',
    'TCU Horned Frogs': '101',
    'Temple Owls': '102',
    'Tennessee Volunteers': '103',
    'Texas A&M Aggies': '105',
    'Texas Longhorns': '104',
    'Texas State Bobcats': '106',
    'Texas Tech Red Raiders': '107',
    'Texas-San Antonio Roadrunners': '119',
    'Toledo Rockets': '108',
    'Troy Trojans': '109',
    'Tulane Green Wave': '110',
    'Tulsa Golden Hurricane': '111',
    'UAB Blazers': '112',
    'UCF Knights': '113',
    'UCLA Bruins': '114',
    'UNLV Rebels': '115',
    'USC Trojans': '096',
    'UTEP Miners': '118',
    'Utah State Aggies': '117',
    'Utah Utes': '116',
    'Vanderbilt Commodores': '120',
    'Virginia Cavaliers': '121',
    'Virginia Tech Hokies': '122',
    'Wake Forest Demon Deacons': '123',
    'Washington Huskies': '124',
    'Washington State Cougars': '125',
    'West Virginia Mountaineers': '126',
    'Western Kentucky Hilltoppers': '127',
    'Western Michigan Broncos': '128',
    'Wisconsin Badgers': '129',
    'Wyoming Cowboys': '130'
         }
