teamCon = {
    'Air Force Falcons': 'Mountain West',
    'Akron Zips': 'MAC',
    'Alabama Crimson Tide': 'SEC',
    'Appalachian State Mountaineers': 'Sun Belt',
    'Arizona State Sun Devils': 'Pac-12',
    'Arizona Wildcats': 'Pac-12',
    'Arkansas Razorbacks': 'SEC',
    'Arkansas State Red Wolves': 'Sun Belt',
    'Army Black Knights': 'Independent',
    'Auburn Tigers': 'SEC',
    'Ball State Cardinals': 'MAC',
    'Baylor Bears': 'Big 12',
    'Boise State Broncos': 'Mountain West',
    'Boston College Eagles': 'ACC',
    'Bowling Green Falcons': 'MAC',
    'Brigham Young Cougars': 'Independent',
    'Buffalo Bulls': 'MAC',
    'California Golden Bears': 'Pac-12',
    'Central Michigan Chippewas': 'MAC',
    'Charlotte 49ers': 'C-USA',
    'Cincinnati Bearcats': 'American',
    'Clemson Tigers': 'ACC',
    'Coastal Carolina Chanticleers': 'Sun Belt',
    'Colorado Buffaloes': 'Pac-12',
    'Colorado State Rams': 'Mountain West',
    'Connecticut Huskies': 'American',
    'Duke Blue Devils': 'ACC',
    'East Carolina Pirates': 'American',
    'Eastern Michigan Eagles': 'MAC',
    'FIU Panthers': 'C-USA',
    'Florida Atlantic Owls': 'C-USA',
    'Florida Gators': 'SEC',
    'Florida State Seminoles': 'ACC',
    'Fresno State Bulldogs': 'Mountain West',
    'Georgia Bulldogs': 'SEC',
    'Georgia Southern Eagles': 'Sun Belt',
    'Georgia State Panthers': 'Sun Belt',
    'Georgia Tech Yellow Jackets': 'ACC',
    'Hawaii Rainbow Warriors': 'Mountain West',
    'Houston Cougars': 'American',
    'Idaho Vandals': 'Independent',
    'Illinois Fighting Illini': 'Big Ten',
    'Indiana Hoosiers': 'Big Ten',
    'Iowa Hawkeyes': 'Big Ten',
    'Iowa State Cyclones': 'Big 12',
    'Kansas Jayhawks': 'Big 12',
    'Kansas State Wildcats': 'Big 12',
    'Kent State Golden Flashes': 'MAC',
    'Kentucky Wildcats': 'SEC',
    'LSU Tigers': 'SEC',
    'Louisiana Tech Bulldogs': 'C-USA',
    "Louisiana-Lafayette Ragin' Cajuns": 'Sun Belt',
    'Louisiana-Monroe Warhawks': 'Sun Belt',
    'Louisville Cardinals': 'ACC',
    'Marshall Thundering Herd': 'C-USA',
    'Maryland Terrapins': 'Big Ten',
    'Massachusetts Minutemen': 'Independent',
    'Memphis Tigers': 'American',
    'Miami (FL) Hurricanes': 'ACC',
    'Miami (OH) RedHawks': 'MAC',
    'Michigan State Spartans': 'Big Ten',
    'Michigan Wolverines': 'Big Ten',
    'Middle Tennessee Blue Raiders': 'C-USA',
    'Minnesota Golden Gophers': 'Big Ten',
    'Mississippi Rebels': 'SEC',
    'Mississippi State Bulldogs': 'SEC',
    'Missouri Tigers': 'SEC',
    'Navy Midshipmen': 'American',
    'Nebraska Cornhuskers': 'Big Ten',
    'Nevada Wolf Pack': 'Mountain West',
    'New Mexico Lobos': 'Mountain West',
    'New Mexico State Aggies': 'Independent',
    'North Carolina State Wolfpack': 'ACC',
    'North Carolina Tar Heels': 'ACC',
    'North Texas Mean Green': 'C-USA',
    'Northern Illinois Huskies': 'MAC',
    'Northwestern Wildcats': 'Big Ten',
    'Notre Dame Fighting Irish': 'Independent',
    'Ohio Bobcats': 'MAC',
    'Ohio State Buckeyes': 'Big Ten',
    'Oklahoma Sooners': 'Big 12',
    'Oklahoma State Cowboys': 'Big 12',
    'Old Dominion Monarchs': 'C-USA',
    'Oregon Ducks': 'Pac-12',
    'Oregon State Beavers': 'Pac-12',
    'Penn State Nittany Lions': 'Big Ten',
    'Pittsburgh Panthers': 'ACC',
    'Purdue Boilermakers': 'Big Ten',
    'Rice Owls': 'C-USA',
    'Rutgers Scarlet Knights': 'Big Ten',
    'San Diego State Aztecs': 'Mountain West',
    'San Jose State Spartans': 'Mountain West',
    'South Alabama Jaguars': 'Sun Belt',
    'South Carolina Gamecocks': 'SEC',
    'South Florida Bulls': 'American',
    'Southern Methodist Mustangs': 'American',
    'Southern Miss Golden Eagles': 'C-USA',
    'Stanford Cardinal': 'Pac-12',
    'Syracuse Orange': 'ACC',
    'TCU Horned Frogs': 'Big 12',
    'Temple Owls': 'American',
    'Tennessee Volunteers': 'SEC',
    'Texas A&M Aggies': 'SEC',
    'Texas Longhorns': 'Big 12',
    'Texas State Bobcats': 'Sun Belt',
    'Texas Tech Red Raiders': 'Big 12',
    'Texas-San Antonio Roadrunners': 'C-USA',
    'Toledo Rockets': 'MAC',
    'Troy Trojans': 'Sun Belt',
    'Tulane Green Wave': 'American',
    'Tulsa Golden Hurricane': 'American',
    'UAB Blazers': 'C-USA',
    'UCF Knights': 'American',
    'UCLA Bruins': 'Pac-12',
    'UNLV Rebels': 'Mountain West',
    'USC Trojans': 'Pac-12',
    'UTEP Miners': 'C-USA',
    'Utah State Aggies': 'Mountain West',
    'Utah Utes': 'Pac-12',
    'Vanderbilt Commodores': 'SEC',
    'Virginia Cavaliers': 'ACC',
    'Virginia Tech Hokies': 'ACC',
    'Wake Forest Demon Deacons': 'ACC',
    'Washington Huskies': 'Pac-12',
    'Washington State Cougars': 'Pac-12',
    'West Virginia Mountaineers': 'Big 12',
    'Western Kentucky Hilltoppers': 'C-USA',
    'Western Michigan Broncos': 'MAC',
    'Wisconsin Badgers': 'Big Ten',
    'Wyoming Cowboys': 'Mountain West'
    }
